In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
# load dataset
df = pd.read_csv('D:/Real Estate Project/flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2264,3 BHK Flat in Adarsh Nagar,https://www.99acres.com/3-bhk-bedroom-apartmen...,Adarsh nagar,65 Lac,"₹ 6,190/sq.ft.",Carpet area: 1050 (97.55 sq.m.),3 Bedrooms,3 Bathrooms,1 Balcony,NaN,"145/12, Adarsh Nagar, Gurgaon, Haryana",1st of 4 Floors,North-West,0 to 1 Year Old,"['Hanuman Mandir', 'Ahooja Eye and Dental Inst...",For sale\n 3bhk & 2 bhk flats\nAdarsh nagar gu...,"['5 Fan', '1 Exhaust Fan', '35 Light', '1 Modu...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN,B69123404
812,3 BHK Flat in Sector 109 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,ATS Kocoon,1.68 Crore,"₹ 9,627/sq.ft.",Super Built up area 1745(162.12 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"N/a, Sector 109 Gurgaon, Gurgaon, Haryana",8th of 20 Floors,North-East,1 to 5 Year Old,"['Jagdish Super Market', 'Dwarka', 'Euro Inter...",This lovely 3 bhk apartment/flat in sector 109...,[],"['Centrally Air Conditioned', 'Security / Fire...","['Green Area5 out of 5', 'Construction5 out of...",X69510728
1464,3 BHK Flat in Sector 66 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Ireo Uptown4.1 ★,2.4 Crore,"₹ 13,064/sq.ft.",Super Built up area 1837(170.66 sq.m.)Built Up...,3 Bedrooms,2 Bathrooms,3 Balconies,Servant Room,"B-5050, Sector 66 Gurgaon, Gurgaon, Haryana",5th of 23 Floors,North-East,1 to 5 Year Old,"['Hub 66', 'Shiksha Bharti Public School', 'VI...",This lovely 3 bhk apartment/flat in sector 66 ...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '1 St...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of...",B69847394
513,2 BHK Flat in Sector 102 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Shapoorji Pallonji Joyville Gurugram4.0 ★,1.2 Crore,"₹ 14,563/sq.ft.",Super Built up area 1359(126.26 sq.m.)Carpet a...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 102 Gurgaon, Gurgaon, Haryana",Ground of 18 Floors,North-East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",This lovely 2 bhk apartment/flat in sector 102...,"['1 Exhaust Fan', '4 AC', '1 Modular Kitchen',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of...",T69179276
2180,2 BHK Flat in Sector 68 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,M3M Sierra 68,1.2 Crore,"₹ 9,000/sq.ft.",Super Built up area 1250(116.13 sq.m.)Carpet a...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"S4/103, Sector 68 Gurgaon, Gurgaon, Haryana",1st of 15 Floors,North,1 to 5 Year Old,"['Airia Mall', 'Sohna Road', 'Golf Course Exte...",My property is located opposite the club house...,"['3 Fan', '1 Fridge', '1 Geyser', '1 Stove', '...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5...",U69787898

In [5]:
# shape
df.shape

(3007, 20)

In [6]:
# info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3007 entries, 0 to 3006
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3007 non-null   str
 1   link             3007 non-null   str
 2   society          3006 non-null   str
 3   price            3006 non-null   str
 4   area             2995 non-null   str
 5   areaWithType     3007 non-null   str
 6   bedRoom          3007 non-null   str
 7   bathroom         3007 non-null   str
 8   balcony          3007 non-null   str
 9   additionalRoom   1693 non-null   str
 10  address          3001 non-null   str
 11  floorNum         3005 non-null   str
 12  facing           2126 non-null   str
 13  agePossession    3006 non-null   str
 14  nearbyLocations  2912 non-null   str
 15  description      3007 non-null   str
 16  furnishDetails   2202 non-null   str
 17  features         2593 non-null   str
 18  rating           2675 non-null   str
 19  property_id      3007 non-null   str
dtypes: str(20)
memory usage: 5.8 MB

In [7]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [8]:
# check for missing values
df.isnull().sum()

property_name         0
link                  0
society               1
price                 1
area                 12
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1314
address               6
floorNum              2
facing              881
agePossession         1
nearbyLocations      95
description           0
furnishDetails      805
features            414
rating              332
property_id           0
dtype: int64

In [9]:
# Columns to drop -> property_name,link,property_id
df.drop(columns=['link','property_id'],inplace=True)

In [10]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [12]:
# rename columns
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [14]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Orchard                                  32
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Signature Global Solera3.7 ★                         27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Supertech Araville                                   18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
M3M Golfestate4.4 ★                                  17
GLS Arawali Homes3.8 ★                               17
M3M Skywalk                                          17
Conscient Heritage Max4.3 ★                          17
Godrej Summit3.7 ★                                   17
HCBS Sports Ville3.6 ★                               16
Pareena Coban Residences                             16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Godrej Oasis3.9 ★                                    15
Ansal Heights 86                                     15
Umang Monsoon Breeze                                 15
Emaar MGF The Palm Drive4.1 ★                        15
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Corona Optus3.9 ★                                    13
M3M Soulitude                                        11
Godrej Aria3.8 ★                                     11
Raheja Vedaanta3.6 ★                                 11
Adani M2K Oyster Grande3.9 ★                         11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
DLF The Skycourt4.2 ★                                11
Breez Global Hill View                               10
Godrej Air                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Pyramid Urban Homes 2                                10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
ILD Greens4.1 ★                                       9
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Altura                                        8
M3M Skycity                                           8
GLS Avenue 51                                         8
M3M Capital                                           8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Birla Navya                                           8
Emaar Imperial Gardens3.8 ★                           7
Mapsko Casa Bella3.8 ★                                7
Sare Crescent Parc Royal Greens Phase 1               7
Signature Global City                                 7
Ansal Housing Highland Park                           7
Trisara Our Homes 3                                   7
Assotech Blith                                        7
AIPL Zen Residences                                   7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Andour Heights3.8 ★                         7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Supertech Hues                                        6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Hero Homes                                            6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Mapsko Royale Ville3.7 ★                              6
Kiran Residency                                       6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Pyramid Urban                                         6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
BPTP Astaire Gardens3.7 ★                             6
Shapoorji Pallonji Joyville Gurugram                  6
Apna Enclave                                          5
Signature Global City 81                              5
Godrej Habitat                                        5
Silverglades The Melia                                5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Central Park Flower Valley Aqua Front Towers          5
Greenopolis                                           5
Green Court3.7 ★                                      5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
M3M The Marina4.0 ★                                   5
Central Park Resorts4.4 ★                             5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Emaar MGF Emerald Estate3.8 ★                         5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Signature Global Grand IVA3.9 ★                       5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
ATS Marigold                                          5
Conscient Elevate                                     5
Krisumi Waterfall Residences                          5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Ramprastha Skyz                                       4
Signature The Serenas                                 4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
Tulip Monsella                                        4
Unitech Vistas                                        4
ILD Grand                                             4
Global Hill View                                      4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Orris Aster Court                                     4
Godrej Icon                                           4
Unitech Fresco3.8 ★                                   4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Godrej Frontier3.7 ★                                  4
Ramprastha Primera                                    4
Sare Petioles                                         4
Corona Gracieux                                       4
Vatika Xpressions                                     3
Raheja Revanta                                        3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Maxworth City Residences                              3
Deepak Minda                                          3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
AFNHB Jalvayu Vihar3.7 ★                              3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
Essel Tower                                           3
Krrish Florence Estate                                3
Piedmont Taksila heights3.6 ★                         3
Tulip White3.5 ★                                      3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Carlton Estate4.0 ★                               3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
Unitech Heritage City                                 3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
Unitech Uniworld Gardens3.8 ★                         3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Vatika Independent Floors3.8 ★                        3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Puri Diplomatic Greens3.9 ★                           3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Apex Our Homes                                        3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Kendriya Vihar4.1 ★                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Spaze Privvy The Address3.9 ★                         3
Shri Ram Apartments                                   3
Tulip Petals3.6 ★                                     3
Sidhartha NCR Greens4.3 ★                             3
Valley View Estate                                    3
The Roselia 2                                         3
Satya Element One                                     3
DLF Royalton Tower                                    3
Smriti Apartment                                      3
Tulsiani Easy in Homes                                2
BPTP Freedom Park Life4.0 ★                           2
Puri The Aravallis                                    2
My Home                                               2
Ramprastha City                                       2
Ardee City3.8 ★                                       2
Supertech Hilltown                                    2
Raheja Vanya                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
M3M Urbana                                            2
Ansal Heights3.2 ★                                    2
Suncity Heights3.7 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Today Callidora                                       2
Park Royal Apartment                                  2
Mapsko Paradise3.9 ★                                  2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Unitech Uniworld Gardens 23.4 ★                       2
Maruti Vihar                                          2
Vasant Appartments                                    2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
Ansal API Celebrity Suites                            2
CGHS Airport Apartment                                2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
BPTP Mansions Park Prime                              2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Housing Board Colony                                  2
Sahara Grace                                          2
Aqua Front Towers                                     2
Oriental Valley CHS                                   2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Ganga Apartment                                       2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
Samaspurkunj                                          2
om appartments                                        2
Lavanya Apartments                                    2
Apartment                                             2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Breeze Global Heights                                 2
Shapoorji Pallonji Joyville                           2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
maa bhagwati residency                                1
Parkwood Westend                                      1
Signature Global Infinity Mall                        1
The Cocoon                                            1
Godrej                                                1
Senate Court                                          1

In [15]:
df['society'].value_counts().shape

(637,)

In [16]:
# By Using Regular Expression
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [17]:
df['society'].value_counts().shape

(603,)

In [18]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
smart world orchard                              32
smart world gems                                 32
emaar mgf emerald floors premier                 32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
la vida by tata housing                          28
godrej nature plus                               27
signature global solera                          27
bptp terra                                       25
emaar gurgaon greens                             25
eldeco accolade                                  24
experion the heartsong                           24
vatika gurgaon                                   24
bestech park view residency                      23
ats triumph                                      22
m3m heights                                      22
tata primanti                                    22
emaar palm gardens                               22
godrej                                           21
rof ananda                                       21
sare crescent parc                               21
experion windchants                              20
sare homes                                       19
antriksh heights                                 19
hcbs sports ville                                18
supertech araville                               18
sobha city                                       18
m3m golfestate                                   18
chd avenue                                       18
ambience creacions                               18
indiabulls centrum park                          18
ats tourmaline                                   18
m3m skywalk                                      18
mapsko mount ville                               18
gls arawali homes                                17
conscient heritage max                           17
godrej summit                                    17
pareena coban residences                         16
m3m merlin                                       16
bestech park view grand spa                      16
ramsons kshitij                                  15
godrej oasis                                     15
ansal heights 86                                 15
umang monsoon breeze                             15
emaar mgf the palm drive                         15
dlf the skycourt                                 15
dlf the primus                                   14
umang winter hills                               14
mvn athens                                       14
indiabulls enigma                                14
ireo victory valley                              14
the close north                                  14
orchid petals                                    14
ireo skyon                                       14
bestech park view ananda                         14
vatika the seven lamps                           14
imperia the esfera                               14
central park flower valley                       13
puri emerald bay                                 13
ats kocoon                                       13
puri diplomatic greens                           13
ireo the corridors                               13
corona optus                                     13
dlf regency park                                 11
m3m soulitude                                    11
godrej aria                                      11
breez global heights                             11
raheja vedaanta                                  11
adani m2k oyster grande                          11
tarc maceo                                       11
sbtl caladium                                    11
alpha corp gurgaonone                            11
bestech park view sanskruti                      11
breez global hill view                           10
ild greens                                       10
godrej air                                       10
pivotal devaan                                   10
emaar mgf palm hills                             10
pyramid urban homes 2                            10
zara aavaas                                      10
ramprastha the edge towers                       10
capital residences 360                           10
signature global synera                          10
bestech park view city                            9
pareena mi casa                                   9
parsvnath green ville                             9
aipl the peaceful homes                           9
vatika city                                       9
microtek greenburg                                9
bestech altura                                    8
m3m skycity                                       8
gls avenue 51                                     8
m3m capital                                       8
emaar digihomes                                   8
orris aster court premier                         8
the lions cghs                                    8
tulip ivory                                       8
vatika lifestyle homes                            8
ss                                                8
avl 36 gurgaon                                    8
birla navya                                       8
emaar imperial gardens                            7
mapsko casa bella                                 7
sare crescent parc royal greens phase 1           7
signature global city                             7
ansal housing highland park                       7
trisara our homes 3                               7
ashiana anmol                                     7
assotech blith                                    7
aipl zen residences                               7
sidhartha ncr one phase                           7
orris carnation residency                         7
sare green parc phase 3                           7
ireo the grand arch                               7
signature andour heights                          7
signature global orchard avenue                   7
vipul lavanya                                     7
supertech hues                                    6
ashiana mulberry                                  6
signature global city 63a                         6
signature the roselia                             6
hero homes                                        6
green court                                       6
suncity vatsal valley                             6
signature global park 4                           6
hsiidc sidco aravali                              6
mapsko royale ville                               6
kiran residency                                   6
bestech park view spa next                        6
parsvnath exotica                                 6
pyramid urban                                     6
m3m sierra 68                                     6
pioneer araya                                     6
bptp astaire gardens                              6
apna enclave                                      5
signature global city 81                          5
godrej habitat                                    5
silverglades the melia                            5
pareena laxmi apartments                          5
satya the hermitage                               5
central park flower valley aqua front towers      5
greenopolis                                       5
signature global the millennia                    5
m3m the marina                                    5
unitech uniworld gardens                          5
central park resorts                              5
signature global city 92                          5
pioneer park                                      5
emaar mgf emerald estate                          5
vatika city homes                                 5
unitech fresco                                    5
dlf park place                                    5
ireo uptown                                       5
signature global grand iva                        5
adani brahma samsara vilasa                       5
signature global city 37d ph 2                    5
ats marigold                                      5
conscient elevate                                 5
krisumi waterfall residences                      5
essel towers                                      5
vatika sovereign park                             5
ramprastha skyz                                   4
signature the serenas                             4
afnhb jalvayu vihar                               4
essel tower                                       4
lotus homz                                        4
tulip monsella                                    4
unitech vistas                                    4
ild grand                                         4
global hill view                                  4
railway officers rpf society                      4
raheja navodaya                                   4
ss the coralwood                                  4
emaar palm heights                                4
krrish provence estate                            4
orris aster court                                 4
godrej icon                                       4
prime habitat                                     4
tata gurgaon gateway                              4
hsiidc sidco shivalik apartments                  4
godrej frontier                                   4
ramprastha primera                                4
kendriya vihar                                    4
dlf the arbour                                    4
sare petioles                                     4
corona gracieux                                   4
vatika xpressions                                 3
raheja revanta                                    3
adani aangan arcade                               3
sare green parc                                   3
chintels paradiso                                 3
maxworth city residences                          3
deepak minda                                      3
unitech the residences                            3
sidhartha ncr one                                 3
raheja sampada                                    3
pyramid elite                                     3
brisk lumbini terrace homes                       3
bhagwati sadan                                    3
krrish florence estate                            3
piedmont taksila heights                          3
tulip white                                       3
sapphire eighty three                             3
dlf the grove                                     3
sukhshanti apartment                              3
ss almeria                                        3
dlf carlton estate                                3
dlf belvedere towers                              3
aipl club residences                              3
unitech heritage city                             3
paras quartier                                    3
ambience lagoon                                   3
raheja atharva                                    3
tulip purple                                      3
vatika independent floors                         3
shree arihant apartment                           3
mahindra aura                                     3
shri banke bihari society                         3
sunischit apartments                              3
dhoot time residency                              3
spaze privy                                       3
tulip lemon                                       3
conscient habitat                                 3
suncity platinum towers                           3
spaze privy at                                    3
apex our homes                                    3
guru gram haryana cghs                            3
siddhartha apartment                              3
whiteland blissville                              3
signature global solera 2                         3
pivotal riddhi siddhi                             3
unitech sunbreeze                                 3
sare green parc 2                                 3
dlf express greens                                3
spaze privvy the address                          3
shri ram apartments                               3
tulip petals                                      3
sidhartha ncr greens                              3
valley view estate                                3
the roselia 2                                     3
satya element one                                 3
dlf royalton tower                                3
smriti apartment                                  3
tulsiani easy in homes                            2
shree shyam residency                             2
bptp freedom park life                            2
puri the aravallis                                2
my home                                           2
ramprastha city                                   2
ardee city                                        2
supertech hilltown                                2
raheja vanya                                      2
vatika inxt floors                                2
palam vihar society                               2
m3m urbana                                        2
ansal heights                                     2
suncity heights                                   2
ramprastha the atrium                             2
today callidora                                   2
park royal apartment                              2
mapsko paradise                                   2
mrg world ultimus                                 2
bptp pedestal                                     2
maruti vihar                                      2
vasant appartments                                2
landmark the residency                            2
mahindra luminare                                 2
the close south                                   2
lagoon apartment                                  2
elan the presidential                             2
pioneer urban presidia                            2
m3m latitude                                      2
ansal api celebrity suites                        2
cghs airport apartment                            2
bestech spa signature                             2
green campus chs                                  2
dlf the crest                                     2
dlf the icon                                      2
professors enclave cghs                           2
bptp mansions park prime                          2
paras irene                                       2
dlf the belaire                                   2
suncity avenue                                    2
bptp amstoria                                     2
emaar mgf the enclave                             2
vipul belmonte                                    2
m3m ikonic                                        2
the penthouses at the hibiscus                    2
ss hibiscus                                       2
viridian the plaza 106                            2
tulip leaf                                        2
vatika emilia floors                              2
emaar mgf palm studios                            2
orchid island                                     2
signature global the millennia 3                  2
m3m sky lofts                                     2
rof aalayas                                       2
awho shanti vihar                                 2
ansal api esencia                                 2
shyam apartment                                   2
raheja atlantis                                   2
central park 2 bellevue                           2
tulip orange                                      2
adani aangan galleria                             2
housing board colony                              2
sahara grace                                      2
aqua front towers                                 2
oriental valley chs                               2
emaar mgf emerald floors                          2
nbcc heights                                      2
supertech hill town                               2
suncity avenue 76                                 2
godrej nature plus serenity                       2
ganga apartment                                   2
suposhaa smartworld orchard                       2
mittal surya vihar                                2
residency grand                                   2
ss residency                                      2
samaspurkunj                                      2
om appartments                                    2
lavanya apartments                                2
apartment                                         2
vipul world floors                                2
milan cghs 9                                      2
element one service                               2
breeze global heights                             2
shapoorji pallonji joyville                       2
dlf city                                          2
silverglades hightown residences                  2
surendra avenue 69                                2
ambience caitriona                                2
sidhivinayak apartments                           2
maa bhagwati residency                            1
parkwood westend                                  1
signature global infinity mall                    1
the cocoon                                        1
senate court                                      1
signature global orchard avenue 2                 1
the new people apartments                         1
the serenas                                       1
central park resort belgravia residences          1
apex builders                                     1
ompee k s residency                               1
bhawna cghs                                       1
ansal sushant lok ci                              1
godrej meridien                                   1
pooja apartment                                   1
gokuldham society, bahadurgarh                    1
4s aradhya homes                                  1
emaar mgf palm terraces                           1
anamika enclave                                   1
huda ashok vihar phase                            1
emaar palm premier                                1
conscient one                                     1
not applicable                                    1
smartworld 1dxp                                   1
czar mahira homes 63a                             1
godrej summit premia towers                       1
m3m one key resiments                             1
sushant lok 1 builder floors                      1
vatika sovereign next sector-82 a gurgaon         1
micasa sec 68                                     1
shyam sadan                                       1
hanumanta apartment                               1
ashiyara 2                                        1
m3m golf hills phase 1                            1
abhinav group housing society                     1
signature signum 95a                              1
aardhya homesh                                    1
sonata group housing society sector 1 manesar     1
experion heartsong                                1
project krishna colony                            1
m3m antalya hills                                 1
malibu towne                                      1
jmd empire                                        1